swagger: '2.0'
info:
  title: Status
  description: Status Dashboard API
  version: "1.0.0"
# the domain of the service
host: example.com
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api/v1
produces:
  - application/json
paths:
  /services:
    get:
      summary: All Services
      description: |
        Returns a list of all configured services.
      tags:
        - Services
      responses:
        200:
          description: An array of services
          schema:
            $ref: '#/definitions/Services'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create Service
      description: Create a new service.
      tags:
        - Services
      responses:
        201:
          description: Service created
          headers:
            Location:
              description: Location of the newly created service
              type: string
  /services/{serviceId}:
    get:
      summary: Service Details
      description: Returns specific service by id.
      tags:
        - Services
      parameters:
        - name: serviceId
          in: path
          required: true
          description: The id of the service to retrieve
          type: string
      responses:
        200:
          description: The requested service
          schema:
            $ref: '#/definitions/Service'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /incidents:
    get:
      summary: Incidents List
      description: Returns a list of all incidents
      tags:
      - Incidents
      responses:
        200:
          description: A list of incidents
          schema:
            type: array
            items:
              $ref: '#/definitions/Incident'
    post:
      summary: Create a new incident
      description: foo
      tags:
        - Incidents
      parameters:
        - name: incident
          in: body
          description: Incident to create
          required: true
          schema:
            $ref: '#/definitions/NewIncident'
      responses:
        200:
          description: foo
definitions:
  Services:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Service'
      bar:
        type: string
  Service:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the service.
      name:
        type: string
        description: Short name for the service.
      description:
        type: string
        description: Description of the service.

  IncidentCommon:
    type: object
    properties:
      title:
        type: string
        description: Title of the incident.
      state:
        type: string
        description: The current state of the incident.
      type:
        type: string
        description: The type of the incident.
      serviceStatusId:
        type: string
        description: The current state of any affected services
      affectedServiceIds:
        type: array
        description: A list of ids of affected services.
        items:
          type: string
          description: The id of an affected service.

  Incident:
    allOf:
    - $ref: '#/definitions/IncidentCommon'
    - required:
      - id
      properties:
        id:
          type: string
          description: Unique identifier for the incident.
        incidentUpdates:
          type: array
          items:
            $ref: '#/definitions/IncidentUpdate'
    
  NewIncident:
    allOf:
    - $ref: '#/definitions/IncidentCommon'
    - required:
      - description
      properties:
        description:
          type: string
          description: Description to be applied to the initial update for the incident.
          
  IncidentUpdate:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for this incident update.
      description:
        type: string
        description: A description for this update.
      state:
        type: string
        description: The new state for this incident and affected services.
      updatedBy:
        type: string
        description: Id of the user who created this incident.
        
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
